/**
 * @ngdoc overview
 * @name hackstack demo app
 *
 * @description
 * Generated by Yo men
 *
 * **Note:** Describe what this module does
 *
 * @example
  http://localhost:8000
 */

angular.module('hackstack demo app', [
  'ngMaterial',
  'ngRoute',
  'hackstack',
  'demo.config'
])
.config([ '$routeProvider', '$locationProvider',
function($routeProvider,$locationProvider) {
    var main = {
      templateUrl: 'routes/main/main.html',
      controller: 'main',
      controllerAs: 'vm'
    };
    $routeProvider
      .when('/mock', main)
      .when('/wrap', main)
      .when('/live', main)
      .otherwise({
        redirectTo: '/live'
      });

    $locationProvider.html5Mode(true);

}])
.run(function(config, hackstack, $location, $log, $window) {
  $window.hsUtils.disableRandomErrors(true);
  config.backendType = $location.path().slice(1) || 'live';
})
